### ISSUE TITLE
말줄임표 사용하기 (text-overflow) + 크로스 브라우징

### ISSUE THREAD

**Issue by sosoYim** [sosoYim/Wiki-For-Frontend-Beginner#21]
08/18 일까지 말줄임표 사용하기 (text-overflow) + 크로스 브라우징 정리해서 올리겠습니다.

**Comment by sosoYim** [comment]
@Hoya-kim 혹시 보시고 의견있으시면 코멘트 부탁드립니다!

**Comment by Hoya-kim** [comment]
@sosoYim 
다 읽어봤습니다! 고생하셨어요!
