### ISSUE TITLE
Negative Margin

### ISSUE THREAD

**Issue by kheeyaa** [sosoYim/Wiki-For-Frontend-Beginner#4]

**Comment by kheeyaa** [comment]
# Negative Margin

## 1. Negative Margin 이란?

> Margin 속성에 음수 값을 주는 것... 근데 그게 왜?
양수 값을 주었을 때랑은 다르게 동작한다! 어떻게 동작하는지 알아보자.

**Comment by Hoya-kim** [comment]
@kheeyaa 감사합니다! 작성하고 PR주세요! 👍
